Started changes for https

diff --git a/root/etc/s6-overlay/s6-rc.d/init-ntfy-config/run b/root/etc/s6-overlay/s6-rc.d/init-ntfy-config/run
--- a/root/etc/s6-overlay/s6-rc.d/init-ntfy-config/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-ntfy-config/run
@@ -1,7 +1,17 @@
 #!/usr/bin/with-contenv bash
 # shellcheck shell=bash
 
-mkdir -p /config
+mkdir -p /config/keys/private &> /dev/null
+
+if [[ -f /config/keys/private/cert.key && -f /config/keys/cert.crt ]]; then
+    echo "using keys found in /config/keys"
+else
+    echo "generating self-signed keys in /config/keys, you can replace these with your own keys if required"
+    rm -f \
+        /config/keys/cert.key \
+        /config/keys/cert.crt || true
+    openssl req -new -x509 -days 3650 -nodes -out /config/keys/cert.crt -keyout /config/keys/private/cert.key
+fi
 
 # permissions
 lsiown -R abc:abc \
